### ISSUE TITLE
clear doesn't clear

### ISSUE THREAD

**Issue by esayre** [paulheider/YouDoneBro#15]
When I push the "clear" button, nothing happens.

**Comment by paulheider** [comment]
Clear is set to work as a long-press rather than an immediate press button.  You need to hold for 2 seconds for clear to work.  If the long-press doesn't work, then I'll add some logging to help diagnose the problem.  I can also add a quick pop-up to notify you when you hit clear but didn't hold it long enough to trigger the wipe.
